### ISSUE TITLE
Nashorn gives an error where client rendering doesn't. Do you know what is wrong? StackOverflow:

### ISSUE THREAD

**Issue by paulwehner** [ssorallen/react-play#6]
http://stackoverflow.com/questions/29429955/error-rendering-react-js-using-jvm-nashorn-play-framework-i-get-null-is-not

**Comment by ssorallen** [comment]
I was able to reproduce this locally. I will do some testing and see if I can figure out what's going wrong.

I noticed your addition of `console = ...` to make console logging possible from inside Nashorn. Would you mind contributing that to the project?

**Comment by paulwehner** [comment]
I just added that edit for console.

**Comment by paulwehner** [comment]
Just tested it, and it works in 8u60 release. For some reason it breaks in the previous releases.

**Comment by ssorallen** [comment]
Thanks for checking the new release. Do you know when that will make it into a Java release?

If a new version of Nashorn solves this problem, I won't investigate any further and instead suggest people upgrade Java versions.

**Comment by ssorallen** [comment]
This was a bug in a specific version of Java. It's far outdated at this point, so I'm closing this.
