### ISSUE TITLE
Versions are old?

### ISSUE THREAD

**Issue by danyaljj** [ssorallen/react-play#9]
The sbt version (play run) and play framework versions are both relatively old. 
Is there any specific reason?

**Comment by ssorallen** [comment]
I created this project when I was building with Play, but I have since been working with it less. The versions have fallen out-of-date because I use Play rarely now.

I am happy to accept pull requests if you are familiar with upgrading versions.

**Comment by JohnReedLOL** [comment]
"I use Play rarely now."

What are you using more of instead of Play?

**Comment by ssorallen** [comment]
@JohnReedLOL My Play usage was short-lived, hence this repo seeing little attention. Rails is my web framework of choice, but I am working primarily in Node and JavaScript at the moment (on the [Nuclide IDE](https://github.com/facebook/nuclide) project).

**Comment by JohnReedLOL** [comment]
@ssorallen I'm kind of split between using your tool and just using Node and doing everything (Elasticsearch, frontend, backed) with Javascript/JSON. The thing is I really don't like Javascript all that much (I don't have auto-complete and I can't remember/learn all the function names so I end up just copy-pasting everything)

**Comment by ssorallen** [comment]
This is now on the 2.5.x release of Play thanks to #10.
